name: Optima OSS Scan
on:
  push:
    tags:
      - 'v*'
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  optima_analyzer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Prepare Gradle
        shell: bash
        env:
          GRADLE_USER_HOME: ${{ runner.temp }}/gradle
          USERNAME: ${{ secrets.ARCHE_BOT_DEV_DEVSTACK_USERNAME }}
          PASSWORD: ${{ secrets.ARCHE_BOT_DEV_DEVSTACK_ARTIFACTORY_TOKEN }}
        run: |
          mkdir -p "$GRADLE_USER_HOME"
          {
            echo "devstackArtifactoryUser=$USERNAME"
            echo "devstackArtifactoryToken=$PASSWORD"
            echo "forceCI=true"
            echo "release=true"
            echo "org.gradle.jvmargs='-Xmx1G'"
          } >> "$GRADLE_USER_HOME/gradle.properties"

      - uses: actions/checkout@v4
      - uses: cariad-optima/optima-actions@v4
        env:
          GRADLE_USER_HOME: ${{ runner.temp }}/gradle
        with:
          toolstation-token: ${{ secrets.OPTIMA_TOKEN }}
          github-token: ${{ secrets.ARCHE_BOT_DEV_GITHUB_CLOUD_TOKEN }}
